In [4]:
from transformers import AutoTokenizer, AutoModel

MODEL_NAME = "answerdotai/ModernBERT-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME)

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.13M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  599MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

[transformers] ModernBertModel LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |  | 
------------------+------------+--+-
decoder.bias      | UNEXPECTED |  | 
head.norm.weight  | UNEXPECTED |  | 
head.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [5]:
tokenizer

TokenizersBackend(name_or_path='answerdotai/ModernBERT-base', vocab_size=50280, model_max_length=8192, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("|||IP_ADDRESS|||", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	1: AddedToken("<|padding|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50254: AddedToken("                        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50255: AddedToken("                       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50256: AddedToken("                      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50257: AddedToken("                     ", rstrip=False, lstrip=False, single_word=False, norm

In [6]:
dir(tokenizer)

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__bool__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_bos_token',
 '_add_eos_token',
 '_add_tokens',
 '_added_tokens_decoder',
 '_added_tokens_encoder',
 '_auto_class',
 '_convert_encoding',
 '_convert_id_to_token',
 '_convert_token_to_id_with_added_voc',
 '_decode',
 '_encode_plus',
 '_eventual_warn_about_too_long_sequence',
 '_extra_special_tokens',
 '_from_pretrained',
 '_get_files_timestamps',
 '_get_padding_truncation_strategies',
 '_in_target_context_manager',
 '_pad',
 '_pad_token_type_id',
 '_patch_mistral_regex',
 '_post_init',
 '_processor_

In [11]:
print(tokenizer.vocab_size)
tokenizer.vocab_files_names

50280


{'tokenizer_file': 'tokenizer.json', 'vocab_file': 'tokenizer.model'}

In [17]:
list(tokenizer.vocab.keys())[10:]


['Ġhorse',
 'Ġafore',
 'Ġisol',
 'ĠMaurice',
 'Known',
 'Functions',
 'ĠVAL',
 'Ġreflect',
 "Ġ''",
 'Ġappointed',
 'ĠCheng',
 'services',
 'ĠComplete',
 'odenal',
 'ĠSamuel',
 'Blood',
 'ĠEEG',
 'colors',
 'Ġnodes',
 '232',
 'calendar',
 'Ġfate',
 'Ġtriang',
 'ĠTerrit',
 'Ġservant',
 'ĠLew',
 'ĠCourts',
 'ection',
 'ano',
 'oslav',
 'cluded',
 'Ġstock',
 'reliable',
 'dden',
 'urer',
 'otransfer',
 'solete',
 'Ġsober',
 'ĠWeiss',
 'Ġgu',
 'ass',
 'nego',
 'Ġclin',
 'ĠElaine',
 'Ġtextbook',
 'Ġtug',
 'ĠReed',
 'etr',
 'ÑĬÑĢ',
 'Ġauf',
 'Roger',
 'ĠPep',
 'urally',
 'âĢ¦âĢ¦âĢ¦âĢ¦',
 'hors',
 'Ġembodied',
 'Ġmetadata',
 'Ġfib',
 'eg',
 'MSCs',
 'Ġuintptr',
 'php',
 'oping',
 'ĠXL',
 'Ġjustified',
 'Ġhackers',
 'JO',
 'haust',
 'borne',
 'ORT',
 'ĠOA',
 'ĠкоÑĤоÑĢ',
 'Ġnumb',
 'Ġpoultry',
 'ENV',
 'Ken',
 'ĠÏĩ',
 'Rx',
 'ring',
 'documentclass',
 'Id',
 'Ġanalyzing',
 'VV',
 'ires',
 'Ġhabeas',
 'Ġsam',
 'ĠKingdom',
 'Ġ"</',
 '¾',
 'alleng',
 'ĠNetflix',
 'Bucket',
 'ĠMissouri',
 'SPEC',

In [22]:
tokenizer.vocab['teleyadhu']

KeyError: 'teleyadhu'

In [23]:
tokenizer.vocab['kya']

KeyError: 'kya'

In [24]:
tokenizer.vocab['what']

5371

In [25]:
model

ModernBertModel(
  (embeddings): ModernBertEmbeddings(
    (tok_embeddings): Embedding(50368, 768, padding_idx=50283)
    (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
    (drop): Dropout(p=0.0, inplace=False)
  )
  (layers): ModuleList(
    (0): ModernBertEncoderLayer(
      (attn_norm): Identity()
      (attn): ModernBertAttention(
        (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
        (Wo): Linear(in_features=768, out_features=768, bias=False)
        (out_drop): Identity()
      )
      (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
      (mlp): ModernBertMLP(
        (Wi): Linear(in_features=768, out_features=2304, bias=False)
        (act): GELUActivation()
        (drop): Dropout(p=0.0, inplace=False)
        (Wo): Linear(in_features=1152, out_features=768, bias=False)
      )
    )
    (1-21): 21 x ModernBertEncoderLayer(
      (attn_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bi

In [26]:
import pandas as pd

data = {
    "text": [
        "Repu NumPy practice chestha.",
        "Help cheyyi CSS.",
        "Main chai pi raha hu.",
        "Best suggestion do JWT ke liye."
    ],
    "label": [0, 1, 0, 1],
    "language": ["te", "te", "hi", "hi"]
}

df = pd.DataFrame(data)

df

,text,label,language
0,Repu NumPy practice chestha.,0,te
1,Help cheyyi CSS.,1,te
2,Main chai pi raha hu.,0,hi
3,Best suggestion do JWT ke liye.,1,hi


In [27]:
text = "Help cheyyi CSS."
tokens = tokenizer.tokenize(text)

tokens

['Help', 'Ġche', 'yy', 'i', 'ĠCSS', '.']

In [28]:
tokenizer(text)

{'input_ids': [50281, 19576, 1161, 12502, 74, 16710, 15, 50282], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [29]:
tokenizer(text, return_tensors="pt")

{'input_ids': tensor([[50281, 19576,  1161, 12502,    74, 16710,    15, 50282]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [30]:
texts = [
    "Help cheyyi CSS.",
    "Best suggestion do JWT ke liye.",
    "Hi"
]

batch = tokenizer(
    texts,
    padding=True
)

batch

{'input_ids': [[50281, 19576, 1161, 12502, 74, 16710, 15, 50282, 50283, 50283, 50283], [50281, 17277, 14876, 513, 500, 16594, 1058, 632, 6683, 15, 50282], [50281, 12764, 50282, 50283, 50283, 50283, 50283, 50283, 50283, 50283, 50283]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]}

In [31]:
import pandas as pd

df = pd.read_csv("help_intent_dataset_v1_12000.csv")

df.head()

,text,label,language
0,Repu NumPy practice chestha.,0,te
1,Help cheyyi CSS.,1,te
2,Main chai pi raha hu.,0,hi
3,Best suggestion do JWT ke liye.,1,hi
4,Main chai pi raha hu.,0,hi


In [32]:
df.shape

(12000, 3)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      12000 non-null  str  
 1   label     12000 non-null  int64
 2   language  12000 non-null  str  
dtypes: int64(1), str(2)
memory usage: 579.5 KB


In [34]:
df["label"].value_counts()

label
0    6000
1    6000
Name: count, dtype: int64

In [35]:
df.isna().sum()

text        0
label       0
language    0
dtype: int64

In [36]:
df.sample(10, random_state=42)

,text,label,language
1935,Help karo RAG me.,1,hi
6494,Oka example cheppu Linux.,1,te
1720,Kal API practice karunga.,0,hi
9120,Aaj mausam accha hai.,0,hi
360,Ivala weather bagundi.,0,te
9663,I watched a movie yesterday.,0,en
5277,Suggest the best way to learn LLM.,1,en
8546,Why is this happening in AWS,1,en
2221,Can you solve this bug,1,en
4617,Kal RAG practice karunga.,0,hi


In [37]:
df["language"].value_counts()

language
te    4000
hi    4000
en    4000
Name: count, dtype: int64

In [38]:
pd.crosstab(df["language"], df["label"])

label,0,1
language,,
en,2000,2000
hi,2000,2000
te,2000,2000


## Preparing the data training and testing/validation

In [40]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

In [41]:
print("Train:", train_df.shape)
print("Validation:", val_df.shape)

print(train_df["label"].value_counts())
print(val_df["label"].value_counts())

Train: (9600, 3)
Validation: (2400, 3)
label
0    4800
1    4800
Name: count, dtype: int64
label
0    1200
1    1200
Name: count, dtype: int64


In [42]:
train_encodings = tokenizer(
    train_df["text"].tolist(),
    padding=True,
    truncation=True,
    return_tensors="pt"
)

In [43]:
val_encodings = tokenizer(
    val_df["text"].tolist(),
    padding=True,
    truncation=True,
    return_tensors="pt"
)

In [44]:
train_encodings.keys()

KeysView({'input_ids': tensor([[50281,    34,  1432,  ...,    15, 50282, 50283],
        [50281, 13030,  3440,  ..., 50283, 50283, 50283],
        [50281,  6802,    86,  ..., 50283, 50283, 50283],
        ...,
        [50281, 13030,   305,  ..., 50283, 50283, 50283],
        [50281, 14569,   310,  ..., 50283, 50283, 50283],
        [50281, 15061,  3331,  ..., 50283, 50283, 50283]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])})

In [45]:
print(train_encodings["input_ids"].shape)
print(train_encodings["attention_mask"].shape)

torch.Size([9600, 13])
torch.Size([9600, 13])


In [46]:
import torch

train_labels = torch.tensor(
    train_df["label"].tolist(),
    dtype=torch.long
)

val_labels = torch.tensor(
    val_df["label"].tolist(),
    dtype=torch.long
)

In [47]:
print(train_labels.shape)
print(val_labels.shape)

torch.Size([9600])
torch.Size([2400])


In [48]:
print(train_encodings["input_ids"].shape)
print(train_encodings["attention_mask"].shape)

print(val_encodings["input_ids"].shape)
print(val_encodings["attention_mask"].shape)

print(train_labels.shape)
print(val_labels.shape)

torch.Size([9600, 13])
torch.Size([9600, 13])
torch.Size([2400, 13])
torch.Size([2400, 13])
torch.Size([9600])
torch.Size([2400])


## Data Loader

In [49]:
from torch.utils.data import TensorDataset

train_dataset = TensorDataset(
    train_encodings["input_ids"],
    train_encodings["attention_mask"],
    train_labels
)

val_dataset = TensorDataset(
    val_encodings["input_ids"],
    val_encodings["attention_mask"],
    val_labels
)

In [50]:
train_dataset[0]

(tensor([50281,    34,  1432,   278,   666,   312,   913, 13420,   419,    74,
            15, 50282, 50283]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 tensor(0))

In [51]:
from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=16,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=16,
    shuffle=False
)

In [53]:
batch = next(iter(train_loader))

print(batch[0].shape) #input sentance
print(batch[1].shape) #attention mask
print(batch[2].shape) # labels

torch.Size([16, 13])
torch.Size([16, 13])
torch.Size([16])


In [54]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     | 
------------------+------------+-
decoder.bias      | UNEXPECTED | 
classifier.weight | MISSING    | 
classifier.bias   | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [55]:
sum(p.numel() for p in model.parameters()) # we are about fine tunne this many parameters

149606402

In [56]:
batch = next(iter(train_loader))

input_ids = batch[0]
attention_mask = batch[1]
labels = batch[2]

In [57]:
outputs = model(
    input_ids=input_ids,
    attention_mask=attention_mask
)

In [60]:
print(outputs.logits.shape)
print(outputs.logits[:5])

torch.Size([16, 2])
tensor([[ 0.0752, -0.7237],
        [-0.7493, -0.7712],
        [ 0.1088, -0.5356],
        [ 0.2651,  0.0276],
        [-0.2308, -0.4384]], grad_fn=<SliceBackward0>)


In [61]:
probs = torch.softmax(outputs.logits, dim=1)

print(probs[:5])

tensor([[0.6898, 0.3102],
        [0.5055, 0.4945],
        [0.6557, 0.3443],
        [0.5591, 0.4409],
        [0.5517, 0.4483]], grad_fn=<SliceBackward0>)


In [62]:
probs = torch.softmax(outputs.logits, dim=1)

print(probs[:5])

tensor([[0.6898, 0.3102],
        [0.5055, 0.4945],
        [0.6557, 0.3443],
        [0.5591, 0.4409],
        [0.5517, 0.4483]], grad_fn=<SliceBackward0>)


In [64]:
labels = batch[2]
print("Predicted:", torch.argmax(probs, dim=1))
print("Actual:   ", labels)

Predicted: tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])
Actual:    tensor([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])


In [65]:
loss_fn = torch.nn.CrossEntropyLoss()

loss = loss_fn(
    outputs.logits,
    labels
)

print(loss)


tensor(0.7038, grad_fn=<NllLossBackward0>)


In [66]:
probs = torch.softmax(outputs.logits, dim=1)

print(probs[:5])

tensor([[0.6898, 0.3102],
        [0.5055, 0.4945],
        [0.6557, 0.3443],
        [0.5591, 0.4409],
        [0.5517, 0.4483]], grad_fn=<SliceBackward0>)


In [67]:
loss_fn = torch.nn.CrossEntropyLoss()

loss = loss_fn(outputs.logits, labels)

print(loss)

tensor(0.7038, grad_fn=<NllLossBackward0>)


In [68]:
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-5
)

In [69]:
old_weight = model.classifier.weight.detach().clone()

In [70]:
model.train()

optimizer.zero_grad()

outputs = model(
    input_ids=input_ids,
    attention_mask=attention_mask
)

loss = loss_fn(outputs.logits, labels)

loss.backward()

optimizer.step()

In [71]:
new_weight = model.classifier.weight.detach().clone()

print(torch.equal(old_weight, new_weight))

False


In [72]:
for batch in train_loader:
    input_ids = batch[0]
    attention_mask = batch[1]
    labels = batch[2]
    
    optimizer.zero_grad()
    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
    )
    loss = loss_fn(outputs.logits, labels)
    
    loss.backward()
    optimizer.step()

In [73]:
model.eval()

ModernBertForSequenceClassification(
  (model): ModernBertModel(
    (embeddings): ModernBertEmbeddings(
      (tok_embeddings): Embedding(50368, 768, padding_idx=50283)
      (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
      (drop): Dropout(p=0.0, inplace=False)
    )
    (layers): ModuleList(
      (0): ModernBertEncoderLayer(
        (attn_norm): Identity()
        (attn): ModernBertAttention(
          (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
          (Wo): Linear(in_features=768, out_features=768, bias=False)
          (out_drop): Identity()
        )
        (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
        (mlp): ModernBertMLP(
          (Wi): Linear(in_features=768, out_features=2304, bias=False)
          (act): GELUActivation()
          (drop): Dropout(p=0.0, inplace=False)
          (Wo): Linear(in_features=1152, out_features=768, bias=False)
        )
      )
      (1-21): 21 x ModernB

In [74]:
correct = 0
total = 0

with torch.no_grad():

    for batch in val_loader:
        input_ids = batch[0]
        attention_mask = batch[1]
        labels = batch[2]

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        predictions = torch.argmax(outputs.logits, dim=1)

        correct += (predictions == labels).sum().item()
        total += labels.size(0)

accuracy = correct / total

print("Validation Accuracy:", accuracy)

Validation Accuracy: 1.0


In [75]:

with torch.no_grad():
    for batch in val_loader:
        input_ids = batch[0]
        attention_mask = batch[1]
        labels = batch[2]

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        probabilities = torch.softmax(outputs.logits, dim=1)
        predictions = torch.argmax(outputs.logits, dim=1)

        for i in range(5):
            print("Actual:", labels[i].item())
            print("Predicted:", predictions[i].item())
            print("Probabilities:", probabilities[i].tolist())
            print()

        break

Actual: 0
Predicted: 0
Probabilities: [0.9999936819076538, 6.310523076535901e-06]

Actual: 1
Predicted: 1
Probabilities: [1.2249236078787362e-06, 0.9999988079071045]

Actual: 0
Predicted: 0
Probabilities: [0.9999996423721313, 3.5159268918505404e-07]

Actual: 1
Predicted: 1
Probabilities: [8.000540674402146e-07, 0.9999991655349731]

Actual: 0
Predicted: 0
Probabilities: [0.9999992847442627, 6.579271598639025e-07]



In [76]:
texts = [
    "what is webkit",
    "how does webkit work",
    "I'm just reading about webkit",
    "hmm this code looks weird",
    "can you explain this error",
    "I think I understand it now",
    "why is my CSS not working",
    "okay let me try this myself"
]
inputs = tokenizer(
    texts,
    padding=True,
    truncation=True,
    return_tensors="pt"
)
with torch.no_grad():
    outputs = model(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"]
    )

    probabilities = torch.softmax(outputs.logits, dim=1)
    predictions = torch.argmax(outputs.logits, dim=1)

In [77]:
for text, prediction, probability in zip(
    texts,
    predictions,
    probabilities
):
    print("Text:", text)
    print("Prediction:", prediction.item())
    print("P(should respond):", probability[1].item())
    print()

Text: what is webkit
Prediction: 1
P(should respond): 0.9999911785125732

Text: how does webkit work
Prediction: 1
P(should respond): 0.9998194575309753

Text: I'm just reading about webkit
Prediction: 0
P(should respond): 0.3929740786552429

Text: hmm this code looks weird
Prediction: 1
P(should respond): 0.9985803365707397

Text: can you explain this error
Prediction: 1
P(should respond): 0.9999270439147949

Text: I think I understand it now
Prediction: 0
P(should respond): 0.1259189248085022

Text: why is my CSS not working
Prediction: 1
P(should respond): 0.9998100399971008

Text: okay let me try this myself
Prediction: 1
P(should respond): 0.9996047616004944



In [78]:
import os

save_path = "./should_ai_respond_model"

os.makedirs(save_path, exist_ok=True)

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("Model saved to:", save_path)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to: ./should_ai_respond_model


In [79]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

loaded_tokenizer = AutoTokenizer.from_pretrained(
    "./should_ai_respond_model"
)

loaded_model = AutoModelForSequenceClassification.from_pretrained(
    "./should_ai_respond_model"
)

loaded_model.eval()

print("Model loaded successfully")

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Model loaded successfully


In [80]:
text = "what is webkit"

inputs = loaded_tokenizer(
    text,
    return_tensors="pt",
    truncation=True
)

with torch.no_grad():
    outputs = loaded_model(**inputs)

probabilities = torch.softmax(outputs.logits, dim=1)

print("P(do not respond):", probabilities[0, 0].item())
print("P(should respond):", probabilities[0, 1].item())

P(do not respond): 8.85702593222959e-06
P(should respond): 0.9999911785125732


In [81]:
def should_respond(text, threshold=0.80):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True
    )

    model.eval()

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=1)

    probability = probabilities[0, 1].item()

    return probability >= threshold, probability

In [82]:
texts = [
    "what is webkit",
    "I'm just reading about webkit",
    "can you explain this error",
    "I think I understand it now",
    "okay let me try this myself"
]

for text in texts:
    respond, probability = should_respond(text)

    print(
        text,
        "=>",
        "RESPOND" if respond else "SILENT",
        f"({probability:.3f})"
    )

what is webkit => RESPOND (1.000)
I'm just reading about webkit => SILENT (0.393)
can you explain this error => RESPOND (1.000)
I think I understand it now => SILENT (0.126)
okay let me try this myself => RESPOND (1.000)


In [85]:
def should_respond(text, eagerness=0.5):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True
    )

    model.eval()

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=1)

    probability = probabilities[0, 1].item()

    threshold = 0.95 - (eagerness * 0.50)

    return probability >= threshold, probability, threshold

In [86]:
texts = [
    "what is webkit",
    "I'm just reading about webkit",
    "can you explain this error",
    "I think I understand it now",
    "okay let me try this myself"
]

for text in texts:
    respond, probability, threshold = should_respond(text)

    print(
        text,
        "=>",
        "RESPOND" if respond else "SILENT",
        f"({probability:.3f})",
        f"({threshold:.3f})"
    )

what is webkit => RESPOND (1.000) (0.700)
I'm just reading about webkit => SILENT (0.393) (0.700)
can you explain this error => RESPOND (1.000) (0.700)
I think I understand it now => SILENT (0.126) (0.700)
okay let me try this myself => RESPOND (1.000) (0.700)


In [87]:
should_respond("okay let me try this myself", 0.1)

(True, 0.9996047616004944, 0.8999999999999999)

In [88]:
## Model redyness

In [89]:
import os

model_path = "./should_ai_respond_model"

total_size = 0

for root, dirs, files in os.walk(model_path):
    for file in files:
        filepath = os.path.join(root, file)
        total_size += os.path.getsize(filepath)

print(f"Model size: {total_size / (1024 ** 2):.2f} MB")

Model size: 574.14 MB


In [90]:
total_params = sum(
    p.numel() for p in loaded_model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in loaded_model.parameters()
    if p.requires_grad
)

print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

Total parameters: 149,606,402
Trainable parameters: 149,606,402


In [91]:
import time
import torch

text = "what is webkit"

inputs = loaded_tokenizer(
    text,
    return_tensors="pt",
    truncation=True
)

loaded_model.eval()

start = time.perf_counter()

with torch.no_grad():
    for _ in range(100):
        outputs = loaded_model(**inputs)

end = time.perf_counter()

print("Average inference time:",
      (end - start) / 100 * 1000,
      "ms")

Average inference time: 77.82964773999993 ms


- 149.6M parameters
- 574 MB disk
- 77.8 ms / inference